# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# locale: en-AU
title: Dorian Tsai
# subtitle: Version 0.1
name: Dorian Tsai
email: dorian.tsai@gmail.com
description: A website about Dorian Tsai, robotics research engineer.
# url: https://jamesmount.tech
repository: doriantsai/doriantsai.github.io
minimal_mistakes_skin: deep_sea
words_per_minute: 200

# Search Settings
search: false

# SEO Related
# google_site_verification: ktrV0f4Jrvrdh-AeYMjp0aMyL3_bg7uamP6IVglHvwc

# Analytics
# analytics:
#   provider: "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
#   google:
#     tracking_id: "UA-180685533-1" # Replace this with your ID, or delete
#     anonymize_ip: true


# Social settings
twitter:
  username: Tsai_D
github:
  username: doriantsai

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
# Outputting
# permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /_posts/page:num/
timezone: Australia/Brisbane

# Include
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author Sidebar Settings
author:
  name   : "Dorian Tsai"
  avatar : "/assets/images/dt_profile.png"
  bio    : "Robotics Research Engineer"
  location: "Brisbane, Australia"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/dorian-tsai/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/tsai_d/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/doriantsai/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "/about_me#contact_me"

# Footer Settings
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/dorian-tsai/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/tsai_d/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/doriantsai/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "/about_me#contact_me"


# Page Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archive Settings
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
